build:
	g++ Dijkstra_matrice_adiacenta.c -o Dijkstra_matrice_adiacenta
	g++ Dijkstra_lista_adiacenta.c -o Dijkstra_lista_adiacenta
run_var1:
	./Dijkstra_matrice_adiacenta
run_var3:
	./Dijkstra_lista_adiacenta
clean:
	rm -rf *.o
